# .github/workflows/ci.yml
name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest with HTML Report
      run: |
        pytest --html=reports/report.html --self-contained-html

    - name: Upload HTML Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: reports/report.html
